name: KnightsAndKings
api: "1.21"
version: 0.1.0
main: net.knightsandkings.knk.paper.KnKPlugin
api-version: "1.21"
depend:
  - WorldGuard
softdepend:
  - WorldEdit
  
commands:
  knk:
    description: KnK admin and debug commands
    usage: /knk help
    permission: knk.admin

  account:
    description: "Manage your in-game account (create, link, view status)"
    usage: "/account [create|link|status]"
    aliases: [acc]
    permission: knk.account.use

  ce:
    description: "Manage custom enchantments on held item"
    usage: "/ce <add|remove|info|cooldown|reload>"
    aliases: [customench]
    permission: customenchantments.command.use
    
permissions:
  knk.admin:
    description: Access to KnK admin commands
    default: op

  # Account management permissions (Phase 4+)
  knk.account.use:
    description: Ability to use /account command (view status)
    default: true

  knk.account.create:
    description: Create account with email/password via /account create
    default: true
    
  knk.account.link:
    description: Generate or consume link codes via /account link
    default: true

  knk.account.admin:
    description: Admin account management (future view/modify other players' accounts)
    default: op

  customenchantments.command.use:
    description: Allows use of /ce root command
    default: true

  customenchantments.command.add:
    description: Allows adding custom enchantments with /ce add
    default: op

  customenchantments.command.remove:
    description: Allows removing custom enchantments with /ce remove
    default: op

  customenchantments.command.info:
    description: Allows viewing custom enchantments with /ce info
    default: true

  customenchantments.command.info.others:
    description: Allows viewing other players' item enchantments with /ce info <player>
    default: op

  customenchantments.command.cooldown.clear:
    description: Allows clearing your own enchantment cooldowns
    default: op

  customenchantments.command.cooldown.clear.others:
    description: Allows clearing other players' enchantment cooldowns
    default: op

  customenchantments.command.reload:
    description: Allows reloading custom enchantment config with /ce reload
    default: op