name: KnightsAndKings
version: 0.1.0
main: net.knightsandkings.knk.paper.KnKPlugin
api-version: "1.21"
depend:
  - WorldGuard
softdepend:
  - WorldEdit
  
commands:
  knk:
    description: KnK admin and debug commands
    usage: /knk help
    permission: knk.admin

  account:
    description: "Manage your in-game account (create, link, view status)"
    usage: "/account [create|link|status]"
    aliases: [acc]
    permission: knk.account.use
    
permissions:
  knk.admin:
    description: Access to KnK admin commands
    default: op

  knk.account.use:
    description: Ability to use /account command
    default: true

  knk.account.create:
    description: Create account with email/password
    default: true

  knk.account.admin:
    description: Admin account management
    default: op
