name: KnightsAndKings
version: 0.1.0
main: net.knightsandkings.knk.paper.KnKPlugin
api-version: "1.21"
depend:
  - WorldGuard
softdepend:
  - WorldEdit
  
commands:
  knk:
    description: KnK admin and debug commands
    usage: /knk help
    permission: knk.admin
    
permissions:
  knk.admin:
    description: Access to KnK admin commands
    default: op
