name: KnightsAndKings
version: 0.1.0
main: net.knightsandkings.knk.paper.KnKPlugin
api-version: "1.21"

commands:
  knk:
    description: KnK admin commands (health, towns, etc)
    usage: /knk health | /knk towns list [page] [size] | /knk town <id>
    permission: knk.admin
  knk-towns:
    description: KnK towns debug commands
    usage: /knk-towns list [page] [size] | /knk-towns town <id>
    permission: knk.admin
    
permissions:
  knk.admin:
    description: Access to KnK admin commands
    default: op
